### ISSUE TITLE
Code crashes when evaluating next move

### ISSUE THREAD

**Issue by marcoprolog** [bcorfman/raven-checkers#18]
Hi Brandon,

I was thinking of using raven-checkers for an experiment, but I'm having issues running the code.
To be more specific it crashes at 
File "C:\Git\raven-checkers\evaluators.py", line 17, in formation_csp
    domains[var] = [item for item in pos_map[var] if board.squares[item] == player + MAN]
KeyError: 21

the problem is that 21 is not a valid index for pos_map, but I'm having a hard time understanding how you calculate the variables for the short_dyke, long_dyke, etc.
Can you help? :)

**Comment by bcorfman** [comment]
The code in the repo is in an exploratory state at the moment. I was trying out some of my ideas for implementing goals and formations, but it's definitely incomplete. For the prior working version, you can go to the main repo page and click on the Releases link. The 0.4 release is what you want.

**Comment by marcoprolog** [comment]
Thank you :)
