### ISSUE TITLE
KeyError during gameplay

### ISSUE THREAD

**Issue by cyrust** [bcorfman/raven-checkers#19]
Using Python 2.7, the following error comes up after Player (human) makes first move (eg: 11-15). The variable pos_map doesn't seem to have 21 in its indices. Ideas for a fix would be appreciated. Please let me know if you can recreate this.

File "evaluators.py", line 17, in formation_csp
    domains[var] = [item for item in pos_map[var] if board.squares[item] == player + MAN]
KeyError: 21

**Comment by cyrust** [comment]
This is probably a simple fix but I'm new to this code so it could be a while until I figure things out.

**Comment by bcorfman** [comment]
Hi - the current repo state is exploratory, so it's not a good one to grab for stability.
Instead, go to the Releases tab and download the 0.4 version. That will work out of the box.

**Comment by cyrust** [comment]
Version 0.4 works fine. Thanks!
